### PR TITLE
Add a Link to a Folder of the Torrents

### PR DESCRIPTION
**Pull request by Edward-Stryfe**
So that way users willing to dedicate some seed time and space will be able to just make a batch download. The link is a btorrent.xyz link of all the torrents as of 10//23//2016

### CODE REVIEW

**Comment by jakefb** [comment]
Hi @Edward-Stryfe thanks for the pull request! Sorry I only just saw this. To clarify, does the folder contain all the .torrent files of the videos or the video files themselves? It's not downloading for me right now, maybe it would be better to host this on the web server as well? I don't think web seeding supports folders yet? I will merge this for now.

**Comment by Edward-Stryfe** [comment]
Sorry yeah I do live streams everynow and then and when I run my Torrent client with Chrome my computer locks up so I have to upload in moderation for the most part I should have everything seeded though. As for webseeding I'm not sure about the folder situation either. I have a folder of the torrents yes and I believe I have all the same torrents seeded on my client as well. Though if you come up with a new batch I'm not going to be able to seed much more cause I'm running out of HDD space atm.

**Comment by jakefb** [comment]
Thanks for making an effort to seed all torrents I appreciate it. In the future we will have to find a way to evenly distribute the network to users, so all the torrents get seeded. Maybe the best way for letting someone seed all the torrents is just to upload a zip file of all the torrent files to the web server and have a link to download that. That could also be web seeded if it was to be downloaded as a torrent.

**Comment by Edward-Stryfe** [comment]
Right that's what this is just instead of zip open so it'd be easier to add specific torrents to the Browser clients. Webseeding is going to be the best thing but I did some looking into it and I didn't see anything about only individual files on the docs page of the website so it may be patched but the server needs to have the CORS enabled in the header so I am not quite sure how to accomplish that and or if you'd need to have a dedicated server for webseeding because of that.

**Comment by jakefb** [comment]
@Edward-Stryfe you need a dedicated server because if you use a ip adress you don't want it to change. The Fastcast web server is set up for webseeding with CORS, so we can use that. Still not sure if you can webseed torrents with multiple files though.

**Pull request merged**
